name: "Jason's Test Site"
favicon: null
layout_spectrum: 0.7084766286425292
typography_spectrum: 0.06874549528583884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.29900795593857765
  lightness: 0.5725652917753905
  saturation: 0.39078096812590957
  rhythmicContrast: 0.8385161710903049
purpose: []
