name: "Jason's Test Site"
favicon: null
layout_spectrum: 0.7084766286425292
typography_spectrum: 0.06874549528583884
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#154792'
    - '#000000'
    - '#e9a746'
    - '#ffffff'
    - '#e41b23'
  brandStrength: 0.29900795593857765
  lightness: 0.6875
  saturation: 0.39078096812590957
  rhythmicContrast: 0.8385161710903049
purpose: []
